[package]
name = "entropy-rs"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12.1"
retable = "0.6.2"
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
zmq = "0.10.0"
